#!/bin/bash 

echo "serveur BNBR"

nmcli con delete id hotspot

nmcli con add con-name hotspot ifname wlan0 type wifi ssid "BNBR-Wifi"
nmcli con modify hotspot 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared

echo "lancement du programe"

